### ISSUE TITLE
咨询下大佬，你这个每次编译咋都是 lc hx3001；我要咋修改才能让他去编译其他机型？谢谢

### ISSUE THREAD

**Issue by shine85** [mjl371/Actions-immortalwrt-mt7981#1]
咨询下大佬，你这个每次编译咋都是 lc hx3001；我要咋修改才能让他去编译其他机型？
然后另1个咋修改让可以进SSH，make menuconfig。谢谢 谢谢 谢谢

**Comment by mjl371** [comment]
actions已经不能ssh了
可以自己修改.config文件选择编译的设备，最好还是自己弄个环境make menuconfig  然后上传.config
